const actionTypes = {
    REGISTER_SUCCESS:"REGISTER_SUCCESS",
    REGISTER_FAILED:"REGISTER_FAIL",
    LOGIN_SUCCESS:"LOGIN_SUCCESS",
    LOGIN_FAIL:"LOGIN_FAIL",
    LOGOUT:"LOGOUT",
    AUTH_ERROR:"AUTH_ERROR",
    CLEAR_ERRORS:"CLEAR_ERRORS",
    GET_USER:"GET_USER",
    GET_USER_PROFILE:'GET_USER_PROFILE',
    GET_USER_PROFILE_FAIL:'GET_USER_PROFILE_FAIL',
    GET_USER_FAIL:"GET_USER_FAIL",
    GET_USERS:"GET_USERS",
    GET_USERS_FAIL:"GET_USERS_FAIL",
    IS_AUTHENTICATED:'IS_AUTHENTICATED',


    CREATE_POST:'CREATE_POST',
    CREATE_POST_FAIL:'CREATE_POST_FAIL',
    GET_POST:'GET_POST',
    GET_POST_FAIL:'GET_POST_FAIL',
    UPDATE_POST:'UPDATE_POST',
    UPDATE_POST_FAIL:'UPDATE_POST_FAIL',
    DELETE_POST:'DELETE_POST',
    DELETE_POST_FAIL:'DELETE_POST_FAIL',
    GET_MY_POSTS:'GET_MY_POSTS',
    GET_MY_POSTS_FAIL:'GET_MY_POSTS_FAIL',
    GET_FEEDS:'GET_FEEDS',
    GET_FEEDS_FAIL:'GET_FEEDS_FAIL',


    CREATE_COMMENT:"CREATE_COMMENT",
    CREATE_COMMENT_FAIL:"CREATE_COMMENT_FAIL",
    GET_A_POST_COMMENT:"GET_A_POST_COMMENT",
    GET_A_POST_COMMENT_FAIL:"GET_A_POST_COMMENT_FAIL",
    UPDATE_COMMENT:'UPDATE_COMMENT',
    UPDATE_COMMENT_FAIL:'UPDATE_COMMENT_FAIL',
    DELETE_COMMENT:'DELETE_COMMENT',
    DELETE_COMMENT_FAIL:'DELETE_COMMENT_FAIL',


    CREATE_LIKE :"CREATE_LIKE",
    CREATE_LIKE_FAIL:'CREATE_LIKE_FAIL',
    REMOVE_LIKE:"REMOVE_LIKE",
    REMOVE_LIKE_FAIL:"REMOVE_LIKE_FAIL",
    GET_LIKES:"GET_LIKES",
    GET_LIKES_FAIL:"GET_LIKES_FAIL",


    CREATE_FOLLOW:'CREATE_FOLLOW',
    CREATE_FOLLOW_FAIL:'CREATE_FOLLOW_FAIL',
    CREATE_UNFOLLOW:'CREATE_UNFOLLOW',
    CREATE_UNFOLLOW_FAIL:'CREATE_UNFOLLOW_FAIL',
    GET_MY_FOLLOWERS:'GET_MY_FOLLOWERS',
    GET_MY_FOLLOWERS_FAIL:'GET_MY_FOLLOWERS'

}

export default actionTypes