const actionTypes = {
    REGISTER_SUCCESS:"REGISTER_SUCCESS",
    REGISTER_FAILED:"REGISTER_FAIL",
    LOGIN_SUCCESS:"LOGIN_SUCCESS",
    LOGIN_FAIL:"LOGIN_FAIL",
    LOGOUT:"LOGOUT",
    AUTH_ERROR:"AUTH_ERROR",
    CLEAR_ERRORS:"CLEAR_ERRORS",
    GET_USER:"GET_USER",
    GET_USER_FAIL:"GET_USER_FAIL",
    GET_USERS:"GET_USERS",
    GET_USER_FAIL:"GET_USER_FAIL",
    IS_AUTHENTICATED:'IS_AUTHENTICATED',

    CREATE_POST:'CREATE_POST',
    CREATE_POST_FAIL:'CREATE_POST_FAIL',
    GET_POST:'GET_POST',
    GET_POST_FAIL:'GET_POST_FAIL',
    UPDATE_POST:'UPDATE_POST',
    UPDATE_POST_FAIL:'UPDATE_POST_FAIL',
    DELETE_POST:'DELETE_POST',
    DELETE_POST_FAIL:'DELETE_POST_FAIL',
    GET_MY_POSTS:'GET_MY_POSTS',
    GET_MY_POSTS_FAIL:'GET_MY_POSTS_FAIL',
}

export default actionTypes