const actionTypes = {
    REGISTER_SUCCESS:"REGISTER_SUCCESS",
    REGISTER_FAILED:"REGISTER_FAIL",
    LOGIN_SUCCESS:"LOGIN_SUCCESS",
    LOGIN_FAIL:"LOGIN_FAIL",
    LOGOUT:"LOGOUT",
    AUTH_ERROR:"AUTH_ERROR",
    CLEAR_ERRORS:"CLEAR_ERRORS",
    GET_USER:"GET_USER",
    GET_USER_FAIL:"GET_USER_FAIL",
    GET_USERS:"GET_USERS",
    GET_USER_FAIL:"GET_USER_FAIL",
    IS_AUTHENTICATED:'IS_AUTHENTICATED',

    NEW_BLOG_POST_SUCCESS:'NEW_BLOG_POST_SUCCESS',
    NEW_BLOG_POST_ERROR:"NEW_BLOG_POST_FAIL",
    GET_BLOG_SUCCESS:"GET_BLOG_SUCCESS",
    GET_BLOG_FAIL:"GET_BLOG_FAIL"
}

export default actionTypes